/*
  SDL2 C++ Wrapper
  Copyright (C) 2020 Malte Kießling <mkalte@mkalte.me>

  This software is provided 'as-is', without any express or implied
  warranty.  In no event will the authors be held liable for any damages
  arising from the use of this software.

  Permission is granted to anyone to use this software for any purpose,
  including commercial applications, and to alter it and redistribute it
  freely, subject to the following restrictions:

  1. The origin of this software must not be misrepresented; you must not
     claim that you wrote the original software. If you use this software
     in a product, an acknowledgment in the product documentation would be
     appreciated but is not required.
  2. Altered source versions must be plainly marked as such, and must not be
     misrepresented as being the original software.
  3. This notice may not be removed or altered from any source distribution.
*/
/**
 * Everything in this file is autogenerated. Please use generateHints to update it! 
 */
#ifndef sdl2wrap_hints_generated
#define sdl2wrap_hints_generated

// always first
#include "base.h"

namespace sdl2wrap {

enum class Hint {
    FramebufferAcceleration = 0,
    RenderDriver = 1,
    RenderOpenglShaders = 2,
    RenderDirect3dThreadsafe = 3,
    RenderDirect3d11Debug = 4,
    RenderLogicalSizeMode = 5,
    RenderScaleQuality = 6,
    RenderVsync = 7,
    VideoAllowScreensaver = 8,
    VideoExternalContext = 9,
    VideoX11Xvidmode = 10,
    VideoX11Xinerama = 11,
    VideoX11Xrandr = 12,
    VideoX11WindowVisualid = 13,
    VideoX11NetWmPing = 14,
    VideoX11NetWmBypassCompositor = 15,
    VideoX11ForceEgl = 16,
    WindowFrameUsableWhileCursorHidden = 17,
    WindowsIntresourceIcon = 18,
    WindowsIntresourceIconSmall = 19,
    WindowsEnableMessageloop = 20,
    GrabKeyboard = 21,
    MouseDoubleClickTime = 22,
    MouseDoubleClickRadius = 23,
    MouseNormalSpeedScale = 24,
    MouseRelativeSpeedScale = 25,
    MouseRelativeModeWarp = 26,
    MouseFocusClickthrough = 27,
    TouchMouseEvents = 28,
    MouseTouchEvents = 29,
    VideoMinimizeOnFocusLoss = 30,
    IdleTimerDisabled = 31,
    Orientations = 32,
    AppleTvControllerUiEvents = 33,
    AppleTvRemoteAllowRotation = 34,
    IosHideHomeIndicator = 35,
    AccelerometerAsJoystick = 36,
    TvRemoteAsJoystick = 37,
    XinputEnabled = 38,
    XinputUseOldJoystickMapping = 39,
    Gamecontrollerconfig = 40,
    GamecontrollerconfigFile = 41,
    GamecontrollerIgnoreDevices = 42,
    GamecontrollerIgnoreDevicesExcept = 43,
    GamecontrollerUseButtonLabels = 44,
    JoystickAllowBackgroundEvents = 45,
    JoystickHidapi = 46,
    JoystickHidapiPs4 = 47,
    JoystickHidapiPs4Rumble = 48,
    JoystickHidapiSteam = 49,
    JoystickHidapiSwitch = 50,
    JoystickHidapiXbox = 51,
    JoystickHidapiGamecube = 52,
    EnableSteamControllers = 53,
    AllowTopmost = 54,
    TimerResolution = 55,
    QtwaylandContentOrientation = 56,
    QtwaylandWindowFlags = 57,
    ThreadStackSize = 58,
    VideoHighdpiDisabled = 59,
    MacCtrlClickEmulateRightClick = 60,
    VideoWinD3dcompiler = 61,
    VideoWindowSharePixelFormat = 62,
    WinrtPrivacyPolicyUrl = 63,
    WinrtPrivacyPolicyLabel = 64,
    WinrtHandleBackButton = 65,
    VideoMacFullscreenSpaces = 66,
    MacBackgroundApp = 67,
    AndroidApkExpansionMainFileVersion = 68,
    AndroidApkExpansionPatchFileVersion = 69,
    ImeInternalEditing = 70,
    AndroidTrapBackButton = 71,
    AndroidBlockOnPause = 72,
    ReturnKeyHidesIme = 73,
    EmscriptenKeyboardElement = 74,
    NoSignalHandlers = 75,
    WindowsNoCloseOnAltF4 = 76,
    BmpSaveLegacyFormat = 77,
    WindowsDisableThreadNaming = 78,
    RpiVideoLayer = 79,
    VideoDoubleBuffer = 80,
    OpenglEsDriver = 81,
    AudioResamplingMode = 82,
    AudioCategory = 83,
    RenderBatching = 84,
    EventLogging = 85,
    WaveRiffChunkSize = 86,
    WaveTruncation = 87,
    WaveFactChunk = 88,
    DisplayUsableBounds = 89,

};

const char* hintToString(Hint hint) noexcept;

#ifdef SDL2WRAP_DEFINITIONS
SDL2WRAP_INLINE const char* hintToString(Hint hint) noexcept
{
    switch (hint) {
    case Hint::FramebufferAcceleration:
        return SDL_HINT_FRAMEBUFFER_ACCELERATION;
    case Hint::RenderDriver:
        return SDL_HINT_RENDER_DRIVER;
    case Hint::RenderOpenglShaders:
        return SDL_HINT_RENDER_OPENGL_SHADERS;
    case Hint::RenderDirect3dThreadsafe:
        return SDL_HINT_RENDER_DIRECT3D_THREADSAFE;
    case Hint::RenderDirect3d11Debug:
        return SDL_HINT_RENDER_DIRECT3D11_DEBUG;
    case Hint::RenderLogicalSizeMode:
        return SDL_HINT_RENDER_LOGICAL_SIZE_MODE;
    case Hint::RenderScaleQuality:
        return SDL_HINT_RENDER_SCALE_QUALITY;
    case Hint::RenderVsync:
        return SDL_HINT_RENDER_VSYNC;
    case Hint::VideoAllowScreensaver:
        return SDL_HINT_VIDEO_ALLOW_SCREENSAVER;
    case Hint::VideoExternalContext:
        return SDL_HINT_VIDEO_EXTERNAL_CONTEXT;
    case Hint::VideoX11Xvidmode:
        return SDL_HINT_VIDEO_X11_XVIDMODE;
    case Hint::VideoX11Xinerama:
        return SDL_HINT_VIDEO_X11_XINERAMA;
    case Hint::VideoX11Xrandr:
        return SDL_HINT_VIDEO_X11_XRANDR;
    case Hint::VideoX11WindowVisualid:
        return SDL_HINT_VIDEO_X11_WINDOW_VISUALID;
    case Hint::VideoX11NetWmPing:
        return SDL_HINT_VIDEO_X11_NET_WM_PING;
    case Hint::VideoX11NetWmBypassCompositor:
        return SDL_HINT_VIDEO_X11_NET_WM_BYPASS_COMPOSITOR;
    case Hint::VideoX11ForceEgl:
        return SDL_HINT_VIDEO_X11_FORCE_EGL;
    case Hint::WindowFrameUsableWhileCursorHidden:
        return SDL_HINT_WINDOW_FRAME_USABLE_WHILE_CURSOR_HIDDEN;
    case Hint::WindowsIntresourceIcon:
        return SDL_HINT_WINDOWS_INTRESOURCE_ICON;
    case Hint::WindowsIntresourceIconSmall:
        return SDL_HINT_WINDOWS_INTRESOURCE_ICON_SMALL;
    case Hint::WindowsEnableMessageloop:
        return SDL_HINT_WINDOWS_ENABLE_MESSAGELOOP;
    case Hint::GrabKeyboard:
        return SDL_HINT_GRAB_KEYBOARD;
    case Hint::MouseDoubleClickTime:
        return SDL_HINT_MOUSE_DOUBLE_CLICK_TIME;
    case Hint::MouseDoubleClickRadius:
        return SDL_HINT_MOUSE_DOUBLE_CLICK_RADIUS;
    case Hint::MouseNormalSpeedScale:
        return SDL_HINT_MOUSE_NORMAL_SPEED_SCALE;
    case Hint::MouseRelativeSpeedScale:
        return SDL_HINT_MOUSE_RELATIVE_SPEED_SCALE;
    case Hint::MouseRelativeModeWarp:
        return SDL_HINT_MOUSE_RELATIVE_MODE_WARP;
    case Hint::MouseFocusClickthrough:
        return SDL_HINT_MOUSE_FOCUS_CLICKTHROUGH;
    case Hint::TouchMouseEvents:
        return SDL_HINT_TOUCH_MOUSE_EVENTS;
    case Hint::MouseTouchEvents:
        return SDL_HINT_MOUSE_TOUCH_EVENTS;
    case Hint::VideoMinimizeOnFocusLoss:
        return SDL_HINT_VIDEO_MINIMIZE_ON_FOCUS_LOSS;
    case Hint::IdleTimerDisabled:
        return SDL_HINT_IDLE_TIMER_DISABLED;
    case Hint::Orientations:
        return SDL_HINT_ORIENTATIONS;
    case Hint::AppleTvControllerUiEvents:
        return SDL_HINT_APPLE_TV_CONTROLLER_UI_EVENTS;
    case Hint::AppleTvRemoteAllowRotation:
        return SDL_HINT_APPLE_TV_REMOTE_ALLOW_ROTATION;
    case Hint::IosHideHomeIndicator:
        return SDL_HINT_IOS_HIDE_HOME_INDICATOR;
    case Hint::AccelerometerAsJoystick:
        return SDL_HINT_ACCELEROMETER_AS_JOYSTICK;
    case Hint::TvRemoteAsJoystick:
        return SDL_HINT_TV_REMOTE_AS_JOYSTICK;
    case Hint::XinputEnabled:
        return SDL_HINT_XINPUT_ENABLED;
    case Hint::XinputUseOldJoystickMapping:
        return SDL_HINT_XINPUT_USE_OLD_JOYSTICK_MAPPING;
    case Hint::Gamecontrollerconfig:
        return SDL_HINT_GAMECONTROLLERCONFIG;
    case Hint::GamecontrollerconfigFile:
        return SDL_HINT_GAMECONTROLLERCONFIG_FILE;
    case Hint::GamecontrollerIgnoreDevices:
        return SDL_HINT_GAMECONTROLLER_IGNORE_DEVICES;
    case Hint::GamecontrollerIgnoreDevicesExcept:
        return SDL_HINT_GAMECONTROLLER_IGNORE_DEVICES_EXCEPT;
    case Hint::GamecontrollerUseButtonLabels:
        return SDL_HINT_GAMECONTROLLER_USE_BUTTON_LABELS;
    case Hint::JoystickAllowBackgroundEvents:
        return SDL_HINT_JOYSTICK_ALLOW_BACKGROUND_EVENTS;
    case Hint::JoystickHidapi:
        return SDL_HINT_JOYSTICK_HIDAPI;
    case Hint::JoystickHidapiPs4:
        return SDL_HINT_JOYSTICK_HIDAPI_PS4;
    case Hint::JoystickHidapiPs4Rumble:
        return SDL_HINT_JOYSTICK_HIDAPI_PS4_RUMBLE;
    case Hint::JoystickHidapiSteam:
        return SDL_HINT_JOYSTICK_HIDAPI_STEAM;
    case Hint::JoystickHidapiSwitch:
        return SDL_HINT_JOYSTICK_HIDAPI_SWITCH;
    case Hint::JoystickHidapiXbox:
        return SDL_HINT_JOYSTICK_HIDAPI_XBOX;
    case Hint::JoystickHidapiGamecube:
        return SDL_HINT_JOYSTICK_HIDAPI_GAMECUBE;
    case Hint::EnableSteamControllers:
        return SDL_HINT_ENABLE_STEAM_CONTROLLERS;
    case Hint::AllowTopmost:
        return SDL_HINT_ALLOW_TOPMOST;
    case Hint::TimerResolution:
        return SDL_HINT_TIMER_RESOLUTION;
    case Hint::QtwaylandContentOrientation:
        return SDL_HINT_QTWAYLAND_CONTENT_ORIENTATION;
    case Hint::QtwaylandWindowFlags:
        return SDL_HINT_QTWAYLAND_WINDOW_FLAGS;
    case Hint::ThreadStackSize:
        return SDL_HINT_THREAD_STACK_SIZE;
    case Hint::VideoHighdpiDisabled:
        return SDL_HINT_VIDEO_HIGHDPI_DISABLED;
    case Hint::MacCtrlClickEmulateRightClick:
        return SDL_HINT_MAC_CTRL_CLICK_EMULATE_RIGHT_CLICK;
    case Hint::VideoWinD3dcompiler:
        return SDL_HINT_VIDEO_WIN_D3DCOMPILER;
    case Hint::VideoWindowSharePixelFormat:
        return SDL_HINT_VIDEO_WINDOW_SHARE_PIXEL_FORMAT;
    case Hint::WinrtPrivacyPolicyUrl:
        return SDL_HINT_WINRT_PRIVACY_POLICY_URL;
    case Hint::WinrtPrivacyPolicyLabel:
        return SDL_HINT_WINRT_PRIVACY_POLICY_LABEL;
    case Hint::WinrtHandleBackButton:
        return SDL_HINT_WINRT_HANDLE_BACK_BUTTON;
    case Hint::VideoMacFullscreenSpaces:
        return SDL_HINT_VIDEO_MAC_FULLSCREEN_SPACES;
    case Hint::MacBackgroundApp:
        return SDL_HINT_MAC_BACKGROUND_APP;
    case Hint::AndroidApkExpansionMainFileVersion:
        return SDL_HINT_ANDROID_APK_EXPANSION_MAIN_FILE_VERSION;
    case Hint::AndroidApkExpansionPatchFileVersion:
        return SDL_HINT_ANDROID_APK_EXPANSION_PATCH_FILE_VERSION;
    case Hint::ImeInternalEditing:
        return SDL_HINT_IME_INTERNAL_EDITING;
    case Hint::AndroidTrapBackButton:
        return SDL_HINT_ANDROID_TRAP_BACK_BUTTON;
    case Hint::AndroidBlockOnPause:
        return SDL_HINT_ANDROID_BLOCK_ON_PAUSE;
    case Hint::ReturnKeyHidesIme:
        return SDL_HINT_RETURN_KEY_HIDES_IME;
    case Hint::EmscriptenKeyboardElement:
        return SDL_HINT_EMSCRIPTEN_KEYBOARD_ELEMENT;
    case Hint::NoSignalHandlers:
        return SDL_HINT_NO_SIGNAL_HANDLERS;
    case Hint::WindowsNoCloseOnAltF4:
        return SDL_HINT_WINDOWS_NO_CLOSE_ON_ALT_F4;
    case Hint::BmpSaveLegacyFormat:
        return SDL_HINT_BMP_SAVE_LEGACY_FORMAT;
    case Hint::WindowsDisableThreadNaming:
        return SDL_HINT_WINDOWS_DISABLE_THREAD_NAMING;
    case Hint::RpiVideoLayer:
        return SDL_HINT_RPI_VIDEO_LAYER;
    case Hint::VideoDoubleBuffer:
        return SDL_HINT_VIDEO_DOUBLE_BUFFER;
    case Hint::OpenglEsDriver:
        return SDL_HINT_OPENGL_ES_DRIVER;
    case Hint::AudioResamplingMode:
        return SDL_HINT_AUDIO_RESAMPLING_MODE;
    case Hint::AudioCategory:
        return SDL_HINT_AUDIO_CATEGORY;
    case Hint::RenderBatching:
        return SDL_HINT_RENDER_BATCHING;
    case Hint::EventLogging:
        return SDL_HINT_EVENT_LOGGING;
    case Hint::WaveRiffChunkSize:
        return SDL_HINT_WAVE_RIFF_CHUNK_SIZE;
    case Hint::WaveTruncation:
        return SDL_HINT_WAVE_TRUNCATION;
    case Hint::WaveFactChunk:
        return SDL_HINT_WAVE_FACT_CHUNK;
    case Hint::DisplayUsableBounds:
        return SDL_HINT_DISPLAY_USABLE_BOUNDS;

    default:
        break;
    };

    return "";
};
#endif // SDL2WRAP_DEFINITIONS

}; //namespace sdl2wrap

#endif // sdl2wrap_hints_generated
